### ISSUE TITLE
from encoding complete to publish - 2 hours gap - why?

### ISSUE THREAD

**Issue by sag333ar** [3speaknetwork/video-encoder#2]
![Screenshot 2022-06-21 at 8 25 13 PM](https://user-images.githubusercontent.com/4737312/174917759-3223860d-c439-41d4-9c21-45c42f16683b.png)

As indicated in above screen-shot, you can clearly see that video encoding was completed at 8:25 PM IST.

Now in the following screen-shot, you can see that it say 7 hours ago (at 6 AM IST next day). 

So, there is 2 hours of gap. What is taking time to publish?

![Screenshot_2022-06-22_at_5 42 40_AM](https://user-images.githubusercontent.com/4737312/174917928-03523c0c-adde-48c5-992f-86110f05cb95.png)

**Comment by vaultec81** [comment]
Going to close this as no longer relevant. Topic of performance/node scoring can be addressed separately and scoped.
